apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.metadata.labels.app }}-app
  name: {{ .Values.metadata.labels.name }}-name
spec:
  replicas: {{.Values.replicacount}}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}-app
    spec:
      containers:
      - image: {{ .Values.spec.image }}  
        name: {{ .Values.metadata.labels.name }}-name
        imagePullPolicy: {{ .Values.spec.pullpolicy }} 
        ports:
        - containerPort: 80
        resources: {}

